### ISSUE TITLE
1パーセントの確率でちんちん

### ISSUE THREAD

**Issue by Lv7Mapper** [Community-in-Clark-High-School/kusurichan#1]
くすりちゃんから

**Comment by PenguinCabinet** [comment]
@Lv7Mapper これTwitter公式のボタン使うの強制?
Twitterのボタンだとレンダリング時にDOMが全部書き換えられるから事前に入れておいたonclickが発火しなくて、動的に書き換えるのは相当難しい。
自前のボタンだったらonclickが発火するから単にJSのif文で分岐すればいいけるけど...

**Comment by Lv7Mapper** [comment]
強制ではないですね
とりあえず練習で簡易的なのをコピペしてきて弄っただけなので

**Comment by PenguinCabinet** [comment]
#2 どうぞ
